# Generated by Django 6.0.3 on 2026-06-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Email', models.EmailField(max_length=60, unique=True)),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Emp_Id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Job', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Contact', models.IntegerField()),
                ('Account', models.CharField(max_length=30)),
                ('Salary', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('Admin_Password', models.CharField(max_length=30, null=True)),
                ('Announcements', models.TextField()),
                ('Complaints', models.TextField()),
                ('Leaves', models.TextField()),
            ],
            options={
                'db_table': 'emp_table',
                'managed': False,
            },
        ),
    ]
